---
apiVersion: v1
kind: Service
metadata:
  name: testing2
  namespace: team1
  labels:
    app: testing2
    service: testing2
spec:
  ports:
  - name: http
    port: 8080
    targetPort: 8080
  selector:
    app: testing2